# Generated by Django 5.0.6 on 2024-06-11 00:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dorm', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('deleted_time', models.DateTimeField(null=True)),
                ('updated_time', models.DateTimeField(null=True)),
                ('deleted_status', models.BooleanField(default=False)),
                ('date', models.DateField()),
                ('hostel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='at_hostel', to='dorm.dropdown')),
                ('marked_by', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='markedby', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('deleted_time', models.DateTimeField(null=True)),
                ('updated_time', models.DateTimeField(null=True)),
                ('deleted_status', models.BooleanField(default=False)),
                ('atd_status', models.CharField(choices=[('P', 'Present'), ('A', 'Absent')], max_length=10)),
                ('attendance', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atd_rec', to='attendence.attendance')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='std_rec', to='dorm.students')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
