# Generated by Django 5.0.6 on 2024-06-25 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendence', '0004_grievance'),
    ]

    operations = [
        migrations.AddField(
            model_name='grievance',
            name='approval_status',
            field=models.BooleanField(default=False),
        ),
    ]
