# Generated by Django 5.0.6 on 2024-06-20 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dorm', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='m_name',
            new_name='name',
        ),
        migrations.AddField(
            model_name='user',
            name='contact',
            field=models.CharField(default=None, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='room_no',
            field=models.CharField(default=None, max_length=5),
            preserve_default=False,
        ),
    ]
