# Generated by Django 5.0.6 on 2024-07-13 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dorm', '0002_rename_m_name_user_name_user_contact_user_room_no'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='contact',
            new_name='dept',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='room_no',
            new_name='room_altd',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='f_name',
            new_name='std_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
        migrations.AddField(
            model_name='user',
            name='f_contact',
            field=models.CharField(default=None, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='m_contact',
            field=models.CharField(default=None, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='seater_altd',
            field=models.CharField(default=None, max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='std_contact',
            field=models.CharField(default=None, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='u_rollno',
            field=models.CharField(default=None, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='year',
            field=models.CharField(default=None, max_length=2),
            preserve_default=False,
        ),
    ]
